exp_dir: exp/FLibriSimulOn_chime

enable_amp: True
do_compile: False

num_epochs: 302000
save_epoch_interval: 100

dataset_args:
  speaker_num: 2338
  train_dataset_args: 
    data_path: "./data/chime/train/feat_24dim_aug.pkl.gz"
    fix_conv_len: 1800
  val_dataset_args: 
    data_path: "./data/chime/dev/feat_24dim_noaug_selectEnroll.pkl.gz"
  test_dataset_args: 
    data_path: "./data/chime/eval/feat_24dim_noaug_selectEnroll.pkl.gz"

dataloader_args:
  batch_size: 8
  shuffle: True
  pin_memory: True

model: ASPVAD
model_args:
  in_dim: 24
  modulation: "FiLM"
  AS_chunk_size: 500
  emb_dim: 40
  emb_num_layers: 4
  feat_num_layers: 4
  att_dim: 8
  pred_spk: False
  checkpoint: "./models/ckpt_librispeech_spk2338.pt"

optimizer: Adam
optimizer_args:
  lr: 0.001

scheduler: StepLR
scheduler_args:
  step_size: 1
  gamma: 0.999