exp_dir: exp/libri_SimulOn_aug

enable_amp: True
do_compile: True

max_steps: 300000
val_interval: 1000
save_interval: 10000

dataset_args:
  speaker_num: 2338
  train_dataset_args:
    data_path: "./data/librispeech/train/feat_24dim_aug.pkl.gz"
  val_dataset_args: 
    data_path: "./data/librispeech/dev/feat_24dim_noaug_selectEnroll.pkl.gz"
  test_dataset_args: 
    data_path: "./data/librispeech/test/feat_24dim_noaug_selectEnroll.pkl.gz"

dataloader_args:
  batch_size: 256
  pin_memory: True
  num_workers: 4
  persistent_workers: True
  prefetch_factor: 2

model: ASPVAD
model_args:
  in_dim: 24
  modulation: "FiLM"
  emb_dim: 40
  emb_num_layers: 4
  feat_num_layers: 4
  att_dim: 8
  AS_chunk_size: 500

optimizer: Adam
optimizer_args:
  lr: 0.01

scheduler: StepLR
scheduler_args:
  step_size: 1
  gamma: 0.99